import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

shell="/bin/bash"

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
